// Copyright 2019 The Go Authors. All rights reserved.
// Use of this source code is governed by a BSD-style
// license that can be found in the LICENSE file.
// 

// WARNING: This file has automatically been generated on Fri, 13 Dec 2019 17:40:24 CST.
// Code generated by https://git.io/c-for-go. DO NOT EDIT.

#include "pthread"
#include <stdlib.h>
#pragma once

#define __CGOGEN 1

