// Copyright 2019 The Go Authors. All rights reserved.
// Use of this source code is governed by a BSD-style
// license that can be found in the LICENSE file.
//

// WARNING: This file has automatically been generated on Tue, 03 Dec 2019 22:25:52 CET.
// Code generated by https://git.io/c-for-go. DO NOT EDIT.

package openbsd
