// Copyright 2019 The Go Authors. All rights reserved.
// Use of this source code is governed by a BSD-style
// license that can be found in the LICENSE file.
//

// WARNING: This file has automatically been generated on Tue, 03 Dec 2019 22:25:52 CET.
// Code generated by https://git.io/c-for-go. DO NOT EDIT.

package openbsd

/*
#include "pthread"
#include <stdlib.h>
#include "cgo_helpers.h"
*/
import "C"
import "unsafe"

// pthreadattr as declared in include/pthread.h:113
type pthreadattr struct {
	stack_addr       unsafe.Pointer
	stack_size       uint
	guard_size       uint
	detach_state     int32
	contention_scope int32
	sched_policy     int32
	sched_param      sched_param
	sched_inherit    int32
	refabfcad8c      *C.pthread_attr_t
	allocsabfcad8c   interface{}
}

// sched_param as declared in include/sched.h:51
type sched_param struct {
	sched_priority int32
	ref6ecda53c    *C.struct_sched_param
	allocs6ecda53c interface{}
}
